version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - greeneye-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    networks:
      - greeneye-network

networks:
  greeneye-network:
    driver: bridge